name: DockerCI
on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Docker Build
        run: docker-compose up -d --build
      - name: Docker Sanity Test
        run: |
          chmod +x ./healthcheck.sh
          ./healthcheck.sh api 8080
        shell: bash
